### ISSUE TITLE
favicon 辨識度很差

### ISSUE THREAD

**Issue by wdzeng** [nycu-life/old-frontend#9]
![image](https://user-images.githubusercontent.com/39057640/155811891-bacb3c4b-6c8b-462d-a55c-63d90738543f.png)

@Yojahuang @LeeLin2602 要不要考慮換一個 = =

**Comment by Cycatz** [comment]
Where does this icon come from?

**Comment by wdzeng** [comment]
> Where does this icon come from?

@LeeLin2602 designed it.

**Comment by Yojahuang** [comment]
Well, actually it’s come from me.

**Comment by Cycatz** [comment]
We need somebody to redesign the icon

**Comment by wdzeng** [comment]
Designing an icon costs a lot.
